#!/usr/bin/python3
#+
# Example use of Qahirah: how to draw ellipses.
#
# Copyright 2015 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# This script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import qahirah as qah
from qahirah import \
    CAIRO, \
    Colour, \
    Matrix, \
    Vector

figure_dimensions = Vector(512, 512)
circle = qah.Path.create_arc \
  (
    centre = (0, 0),
    radius = figure_dimensions.x / 2,
    angle1 = 0,
    angle2 = qah.circle,
    negative = False,
    closed = True
  )

def figure_1(g) :
    nr_steps = 5
    for step in range(nr_steps) :
        angle = step / nr_steps * qah.circle / 2
        (circle
            .transform
              (
                    Matrix.rotate(angle)
                *
                    Matrix.scale(Vector(0.25, 1))
              )
            .draw(g)
        )
        g.stroke()
    #end for
#end figure_1

def figure_2(g) :
    nr_steps = 7
    for step in range(nr_steps) :
        (circle
            .transform
              (
                Matrix.scale
                  (
                    Vector
                      (
                        x = min(2 * (step + 1) / nr_steps, 1),
                        y = min(2 * (nr_steps - step) / nr_steps, 1)
                      )
                  )
              )
            .draw(g)
        )
        g.stroke()
    #end for
#end figure_2

def figure_3(g) :
    g.save()
    g.rotate(- 45 * qah.deg)
    nr_steps = 8
    for step in range(nr_steps) :
        (circle
            .transform
              (
                Matrix.scale
                  (
                    Vector
                      (
                        x = (step + 1) / nr_steps,
                        y = (nr_steps - step) / nr_steps
                      )
                  )
              )
            .draw(g)
        )
        g.stroke()
    #end for
    g.restore()
#end figure_3

nr_figures = 3
margin = Vector(20, 20)
pix = qah.ImageSurface.create \
  (
    format = CAIRO.FORMAT_RGB24,
    dimensions = Vector(nr_figures, 1) * (figure_dimensions + margin) + margin
  )
g = \
    (qah.Context.create(pix)
        .set_source_colour(Colour.from_hsva((0.13, 0.05, 1)))
        .paint()
        .set_source_colour(Colour.grey(0, 1))
    )
col = 0
for \
    figure, colour, line_thickness \
in \
    (
        (figure_1, Colour.from_hsva((0.1, 0.9, 0.4)), 8),
        (figure_2, Colour.from_hsva((0.5, 0.9, 0.4)), 6),
        (figure_3, Colour.from_hsva((0.3, 0.9, 0.4)), 4),
    ) \
 :
    g.matrix = Matrix.translate(Vector(col + 0.5, 0.5) * (figure_dimensions + margin) + margin / 2)
    g.source_colour = colour
    g.line_width = line_thickness
    figure(g)
    col += 1
#end for
pix.write_to_png("{}.png".format(os.path.basename(sys.argv[0])))
