#!/usr/bin/python3
#+
# Generate a tree-like figure from an interated function system.
#
# Copyright 2016 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import qahirah as qah
from qahirah import \
    CAIRO, \
    Colour, \
    Matrix, \
    Path, \
    Vector
Pt = Path.Point

def do_pattern(g, element_action, subtransforms, nest) :
    "general routine for drawing IFS figures. element_action draws the basic" \
    " figure, while subtransforms is a sequence of Matrix transformations to" \
    " apply to recursive subfigures."
    element_action(g)
    if nest > 0 :
        save_matrix = g.matrix
        for subtransform in subtransforms :
            g.transform(subtransform)
            do_pattern(g, element_action, subtransforms, nest - 1)
            g.matrix = save_matrix
        #end for
    #end if
#edn do_pattern

def do_line_pattern(g, nest) :
    "draws the original tree pattern, from a PostScript program I got from" \
    " somewhere back in 1988."

    def pattern_element_line(g) :
        (g
            .move_to((0, 0))
            .line_to((0, 1))
        )
    #end pattern_element_line

#begin do_line_pattern
    do_pattern \
      (
        g = g,
        element_action = pattern_element_line,
        subtransforms =
            [
                    Matrix.translate((0, 1 / 3))
                *
                    Matrix.scale(0.75)
                *
                    Matrix.rotate(30 * qah.deg),
                    Matrix.translate((0, 2 / 3))
                *
                    Matrix.scale(0.75)
                *
                    Matrix.rotate(-35 * qah.deg),
                    Matrix.translate((0, 1))
                *
                    Matrix.scale(0.5)
                *
                    Matrix.rotate(45 * qah.deg),
            ],
        nest = nest
      )
    g.stroke()
      # The original PostScript version had to be careful not to exceed
      # path-length limits. So do_pattern had to do periodic stroke calls
      # itself. With Cairo, I don’t have to worry, so I only need one
      # stroke call at the end.
#end do_line_pattern

def do_curvy_pattern(g, nest) :
    "pattern based on <http://www.jdawiseman.com/2015/20150219_TriangleTree.pdf>" \
    " by Julian Wiseman, as mentioned in" \
    " <https://groups.google.com/d/msg/comp.lang.postscript/Y8Txg8MOnNw/SAjM9YHKRrIJ>."

    frac = 0.3
    thick = Vector(-1, 1) * 0.02
    curve_seg = Path \
      (
        [
            Path.Segment
              (
                [
                    Pt((frac, 1), False),
                    Pt(Vector(frac, frac) - thick, True),
                    Pt(Vector(frac, frac) - thick, True),
                    Pt((-1, frac), False),
                    Pt(Vector(frac, frac) + thick, True),
                    Pt(Vector(frac, frac) + thick, True),
                ],
                True
              ),
        ]
      )

    def pattern_element_curvy(g) :
        g.new_path()
        for i in range(4) :
            g.append_path \
              (
                curve_seg,
                    Matrix.rotate(i / 4 * qah.circle)
                *
                    Matrix.scale(0.25)
              )
        #end for
        g.fill()
    #end pattern_element_curvy

#begin do_curvy_pattern
    save_matrix = g.matrix
    g.transform \
      (
            Matrix.translate((0.5, frac + 0.2))
        *
            Matrix.rotate(-30 * qah.deg)
      )
    do_pattern \
      (
        g = g,
        element_action = pattern_element_curvy,
        subtransforms =
            [
                    Matrix.scale(0.5)
                *
                    Matrix.translate(Vector(frac - 0.15, 1.55) / 2)
                *
                    Matrix.rotate(-60 * qah.deg),
                    Matrix.scale(0.85)
                *
                    Matrix.translate(Vector(-0.75, frac + 0.4) / 2)
                *
                    Matrix.rotate(30 * qah.deg),
            ],
        nest = nest
      )
    g.matrix = save_matrix
#end do_curvy_pattern

dpi = 144
figure_scale = 200
image_bounds = Vector(600, 450)
pix = qah.ImageSurface.create \
  (
    format = CAIRO.FORMAT_RGB24,
    dimensions = round(image_bounds * dpi / qah.base_dpi)
  )
g = \
    (qah.Context.create(pix)
        .scale(dpi / qah.base_dpi)
        .set_source_colour(Colour.grey(1))
        .paint()
        .set_source_colour(Colour.grey(0))
        .scale(figure_scale)
        .transform(Matrix.scale((1, -1), centre = (0, 1.1)))
          # flip from PostScript to Cairo coordinates
        .set_line_width(0.5 / figure_scale)
        .translate((1.4, 0.05))
    )
#do_line_pattern(g, 10)
do_curvy_pattern(g, 10)

pix.flush().write_to_png("{}.png".format(os.path.basename(sys.argv[0])))
