#!/usr/bin/python3
#+
# A simulation of random noise on top of an image.
#
# Copyright 2015 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import array
import random
import qahirah as qah
from qahirah import \
    CAIRO, \
    Colour, \
    Matrix, \
    Rect, \
    Vector

#+
# Sample image & noise
#-

def make_sample_image() :
    aspect = Vector(4, 3)
    res_scale = 192
    circle_radius = 1.4
    grid_unit = circle_radius / 6
    src = qah.ImageSurface.create \
      (
        format = CAIRO.FORMAT_RGB24,
        dimensions = aspect * res_scale
      )
    ctx = \
        (qah.Context.create(src)
            .set_matrix(Matrix.scale(res_scale) * Matrix.translate(aspect / 2))
            .set_source_colour(Colour.grey(.5))
            .set_operator(CAIRO.OPERATOR_SOURCE)
            .paint()
            .arc(centre = (0, 0), radius = circle_radius, angle1 = 0, angle2 = qah.circle)
            .clip()
            .set_source_colour(Colour.grey(0))
            .paint()
            .set_source_colour(Colour.grey(1))
            .rectangle(Rect(- circle_radius, - grid_unit * 6.5, 2 * circle_radius, 3 * grid_unit))
            .fill()
            .rectangle(Rect(- circle_radius, 3 * grid_unit, 2 * circle_radius, grid_unit))
            .fill()
        )
    for i in range(6) :
        ctx.rectangle \
          (
                Rect(0, 0, grid_unit * 2, grid_unit * 2)
            +
                Vector(i * grid_unit * 2 - circle_radius, - grid_unit * 2.5)
          )
        ctx.source_colour = Colour.from_rgba \
          (
            (
                (1, 0, 0, 1, 1, 0)[i],
                (1, 1, 1, 0, 0, 0)[i],
                (0, 1, 0, 1, 0, 1)[i],
            )
          )
        ctx.fill()
        ctx.rectangle \
          (
                Rect(0, 0, grid_unit * 2, grid_unit)
            +
                Vector(i * grid_unit * 2 - circle_radius, grid_unit * 2)
          )
        ctx.source_colour = Colour.grey(i / 5)
        ctx.fill()
    #end for
    ctx.reset_clip()
    pastel_blue = Colour.from_hsva((0.58, 0.66, 0.74))
    pastel_green_dark = Colour.from_hsva((0.42, 0.66, 0.74))
    pastel_pink = Colour.from_hsva((0.91, 0.66, 0.74))
    pastel_green_light = Colour.from_hsva((0.25, 0.66, 0.74))
    pastel_purple = Colour.from_hsva((0.75, 0.66, 0.74))
    pastel_gold = Colour.from_hsva((0.08, 0.66, 0.74))
    for \
        rect, colour \
    in \
        (
            (Rect(-7, -6, 0.95, 1.95), pastel_blue),
            (Rect(-8, -6, 0.95, 5.95), pastel_green_dark),
            (Rect(-8, 0, 0.95, 5.95), pastel_pink),
            (Rect(-7, 4, 0.95, 1.95), pastel_gold),
            (Rect(6, -6, 0.95, 1.95), pastel_blue),
            (Rect(7, -6, 0.95, 5.95), pastel_green_light),
            (Rect(7, 0, 0.95, 5.95), pastel_purple),
            (Rect(6, 4, 0.95, 1.95), pastel_gold),
        ) \
    :
        (ctx.rectangle(rect * grid_unit)
            .set_source_colour(colour)
            .fill()
        )
    #end for
    src.flush()
    return \
        src
#end make_sample_image

def make_noise_pat() :
    random.seed(999) # want same sequence every time
    pat_size = 256
    patbytes = array.array("I", (0,) * (pat_size * pat_size))
      # compute by longwords rather than bytes, so result is endian-independent
    assert patbytes.itemsize == 4 # in case of any doubt--docs seem a little unclear on this point
    for i in range(len(patbytes)) :
        a = 255 # ignored
        r = random.randrange(256)
        g = random.randrange(256)
        b = random.randrange(256)
        patbytes[i] = a << 24 | r << 16 | g << 8 | b
    #end i
    return \
        (qah.Pattern.create_for_surface
          (
            qah.ImageSurface.create_for_array
              (
                arr = patbytes,
                format = CAIRO.FORMAT_RGB24,
                dimensions = (pat_size, pat_size),
                stride = 4 * pat_size
              )
          )
          .set_extend(CAIRO.EXTEND_REPEAT)
          .set_matrix(Matrix.scale(0.5)) # make the noise coarser
        )
#end make_noise_pat

#+
# Mainline
#-

src = make_sample_image()
noise_pat = make_noise_pat()
noise_strength = 0.5 # feel free to play with this
dst = src.create_like()
(qah.Context.create(dst)
    .set_source(qah.Pattern.create_for_surface(src))
    .set_operator(CAIRO.OPERATOR_SOURCE)
    .paint()
    .set_source(noise_pat)
    .set_operator(CAIRO.OPERATOR_DIFFERENCE) # closest I can get to a bitwise-xor effect
    .paint_with_alpha(noise_strength)
)
dst \
    .flush() \
    .write_to_png("{}.png".format(os.path.basename(sys.argv[0])))
