#!/usr/bin/python3
#+
# Example use of Qahirah: various fun things with paths.
#
# Copyright 2015 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
# This script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import qahirah as qah
from qahirah import \
    CAIRO, \
    circle, \
    Colour, \
    Matrix, \
    Rect

nr_figures = 5

pat = qah.Pattern.create_linear \
  (
    p0 = (0, 0),
    p1 = (1, 1),
    colour_stops =
        (
            (0, Colour.from_hsva((0.6, 0.9, 0.7))),
            (0.5, Colour.from_hsva((0.1, 0.9, 0.9))),
            (0, Colour.from_hsva((0.6, 0.9, 0.7))),
        )
  )
pat.extend = CAIRO.EXTEND_REPEAT
pat.matrix = Rect.from_dimensions((1, 1)).transform_to(Rect.from_dimensions((0.1, 0.1)))

pix = qah.ImageSurface.create \
  (
    format = CAIRO.FORMAT_RGB24,
    dimensions = (600, 600)
  )
g = qah.Context.create(pix)
origin_to_centre = Matrix.translate(pix.dimensions / 2)
angle_step = circle / nr_figures
offset_from_origin = Matrix.translate((0, 70))

# create path
shape = \
    (g
        .new_path()
        .arc(centre = (0, 65), radius = 35, angle1 = 0, angle2 = circle)
        .new_sub_path()
        .arc(centre = (0, 35), radius = 35, angle1 = 0, angle2 = circle)
    ).copy_path().transform(Matrix.scale(2))
# sys.stderr.write(repr(list(shape.elements)) + "\n") # debug

# now do the actual drawing
(g
    .set_operator(CAIRO.OPERATOR_SOURCE)
    .set_source_colour(Colour.grey(1))
    .paint()
    .set_source_colour(Colour.from_hsva((0.4, 0.9, 0.4)))
)

(g
    .set_matrix(origin_to_centre * Matrix.rotate(angle_step) * offset_from_origin)
    .new_path()
    .append_path(shape)
    .set_dash(((5, 2, 5, 2, 5, 2, 2, 2, 2, 2, 2, 2), 0))
    .set_line_width(10)
    .set_line_cap(CAIRO.LINE_CAP_BUTT)
    .stroke()
).dash = ((), 0)

g.matrix = g.matrix = origin_to_centre * Matrix.rotate(2 * angle_step) * offset_from_origin
g.new_path()
g.append_path(shape)
g.dash = ((5, 8, 2, 8), 0)
g.line_width = 4
g.line_cap = CAIRO.LINE_CAP_ROUND
g.stroke()
g.dash = ((), 0)

g.matrix = g.matrix = origin_to_centre * Matrix.rotate(3 * angle_step) * offset_from_origin
g.new_path()
g.append_path(shape)
g.dash = ((5, 8, 2, 8), 0)
g.line_width = 5
g.line_cap = CAIRO.LINE_CAP_SQUARE
g.stroke()
g.dash = ((), 0)

g.source = pat

g.matrix = g.matrix = origin_to_centre * Matrix.rotate(4 * angle_step) * offset_from_origin
g.new_path()
g.append_path(shape)
g.fill_rule = CAIRO.FILL_RULE_WINDING
g.fill()

g.matrix = g.matrix = origin_to_centre * Matrix.rotate(0 * angle_step) * offset_from_origin
g.new_path()
g.append_path(shape)
g.fill_rule = CAIRO.FILL_RULE_EVEN_ODD
g.fill()

pix.flush()
pix.write_to_png("%s.png" % os.path.basename(sys.argv[0]))
