#!/usr/bin/python3
#+
# Try some Truchet tilings, based on
# <http://mathworld.wolfram.com/TruchetTiling.html>. The basic
# principle is that the sides of a rectangular cell are grouped into
# two pairs of adjacent sides, such that the pattern in each cell will
# join seamlessly across an adjacent cell where the common sides come
# from the same pair.
#
# The variety in the pattern is provided by randomly reflecting each
# cell about the x- or y-axes, or both, or neither. It is better to
# think of it as a combination of reflections rather than a rotation,
# to allow for non-square cells, and also to generalize to higher
# dimensions.
#
# Copyright 2016 by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>. This
# script is licensed CC0
# <https://creativecommons.org/publicdomain/zero/1.0/>; do with it
# what you will.
#-

import sys
import os
import math
import qahirah as qah
from qahirah import \
    CAIRO, \
    Colour, \
    Context, \
    Matrix, \
    Vector

#+
# Useful stuff
#-

class RubbishRandom :
    "a very crude random-number generator. The purpose of using this is to" \
    " ensure all runs of this sample program will produce exactly the same output."

    def __init__(self, seed) :
        self.seed = seed
    #end __init__

    def random(self) :
        "returns a random float in the range [0 .. 1)."
        # algorithm is that of the good old BSD linear-congruential pseudo-random number generator.
        self.seed = (1103515245 * self.seed + 12345) % (1 << 31)
        return \
            self.seed / (1 << 31)
    #end random

    def randrange(self, upper) :
        "returns a random integer in range(upper)."
        return \
            math.trunc(self.random() * upper)
    #end randrange

    def choice(self, seq) :
        "returns a random item from a sequence."
        return \
            seq[self.randrange(len(seq))]
    #end choice

#end RubbishRandom

#+
# The tilings
#-

class TruchetActions :
    "temp namespace to collect different types of Truchet tiles." \
    " Each action takes 3 args: the Context into which to draw the tile," \
    " and two opposite corner points of the cell, notionally the top-left" \
    " and bottom-right."

    def diag_tile(g : Context, p1 : Vector, p2 : Vector) :
        "half-filled squares."
        (g
            .move_to((p2.x, p1.y))
            .line_to(p2)
            .line_to((p1.x, p2.y))
            .close_path()
            .fill()
        )
    #end diag_tile

    def sector_tile(g : Context, p1 : Vector, p2 : Vector) :
        "filled quarter-circle."
        radius = abs(p2 - p1) / math.sqrt(2)
        (g
            .move_to(p2)
            .arc
              (
                centre = p2,
                radius = radius,
                angle1 = 180 * qah.deg,
                angle2 = 270 * qah.deg,
                negative = False
              )
            .fill()
        )
    #end sector_tile

    def hollow_sector_tile(g : Context, p1 : Vector, p2 : Vector) :
        "filled quarter-circle with hole in middle."
        inset = 0.15
        cell_radius = abs(p2 - p1) / math.sqrt(2)
        outer_radius = cell_radius * (1 - inset)
        inner_radius = cell_radius * inset
        (g
            .move_to(p2)
            .arc
              (
                centre = p2,
                radius = outer_radius,
                angle1 = 180 * qah.deg,
                angle2 = 270 * qah.deg,
                negative = False
              )
            .line_to(p2 + (p1 - p2) * Vector(0, inner_radius))
            .arc
              (
                centre = p2,
                radius = inner_radius,
                angle1 = 270 * qah.deg,
                angle2 = 180 * qah.deg,
                negative = True
              )
            .close_path()
            .fill()
        )
    #end hollow_sector_tile

    def arc_tile(g : Context, p1 : Vector, p2 : Vector) :
        "circular arcs."
        radius = abs(p2 - p1) / math.sqrt(8)
        (g
            .arc
              (
                centre = p1,
                radius = radius,
                angle1 = 0,
                angle2 = 90 * qah.deg,
                negative = False
              )
            .stroke()
            .arc
              (
                centre = p2,
                radius = radius,
                angle1 = 180 * qah.deg,
                angle2 = 270 * qah.deg,
                negative = False
              )
            .stroke()
        )
    #end arc_tile

    def corner_tile(g : Context, p1 : Vector, p2 : Vector) :
        "angular arc."
        p1a = Vector(p1.x, p2.y)
        p2a = Vector(p2.x, p1.y)
        frac = 3 / 8
        (g
            .move_to((p1 + p2a) / 2)
            .line_to(p1 + (p2 - p1) * frac)
            .line_to((p1 + p1a) / 2)
            .stroke()
            .move_to((p2 + p2a) / 2)
            .line_to(p2 + (p1 - p2) * frac)
            .line_to((p2 + p1a) / 2)
            .stroke()
        )
    #end corner_tile

    def def_diag_stripes_tile(frac : float) :

        def diag_stripes_tile(g : Context, p1 : Vector, p2 : Vector) :
            "two symmetrical diagonal stripes."
            p1a = Vector(p1.x, p2.y)
            p2a = Vector(p2.x, p1.y)
            (g
                .move_to(p1 + (p2a - p1) * frac)
                .line_to(p1 + (p1a - p1) * frac)
                .stroke()
                .move_to(p2 + (p2a - p2) * frac)
                .line_to(p2 + (p1a - p2) * frac)
                .stroke()
            )
        #end diag_stripes_tile

    #begin def_diag_stripes_tile
        return \
            diag_stripes_tile
    #end def_diag_stripes_tile

    def corner_stripes_tile(g : Context, p1 : Vector, p2 : Vector) :
        "two diagonal stripes close to one corner."
        p1a = Vector(p1.x, p2.y)
        p2a = Vector(p2.x, p1.y)
        frac = 0.25
        (g
            .move_to(p1 + (p2a - p1) * frac)
            .line_to(p1 + (p1a - p1) * frac)
            .stroke()
            .move_to(p1 + (p2a - p1) * (1 - frac))
            .line_to(p1 + (p1a - p1) * (1 - frac))
            .stroke()
        )
    #end corner_stripes_tile

    def cross_tile(g : Context, p1 : Vector, p2 : Vector) :
        "two lines crossing."
        p1a = Vector(p1.x, p2.y)
        p2a = Vector(p2.x, p1.y)
        frac = 0.3
        (g
            .move_to(p1 + (p2a - p1) * frac)
            .line_to(p1 + (p1a - p1) * (1 - frac))
            .stroke()
            .move_to(p1 + (p2a - p1) * (1 - frac))
            .line_to(p1 + (p1a - p1) * frac)
            .stroke()
        )
    #end cross_tile

    types = \
        [
            diag_tile,
            sector_tile,
            hollow_sector_tile,
            arc_tile,
            def_diag_stripes_tile(0.5),
            def_diag_stripes_tile(0.8),
            #corner_tile,
            corner_stripes_tile,
            cross_tile,
        ]

#end TruchetActions

truchet_types = TruchetActions.types
del TruchetActions

def draw_truchet(g : Context, do_tile, total_dimensions : Vector, nr_tiles : Vector) :
    "fills in a Truchet tiling of the specified type and number of tiles within the bounds" \
    " with corners (0, 0) and total_dimensions."
    assert nr_tiles.isint() and nr_tiles.x > 0 and nr_tiles.y > 0
    tile_dimensions = total_dimensions / nr_tiles
    save_matrix = g.matrix
    for x in range(nr_tiles.x) :
        for y in range(nr_tiles.y) :
            p1 = tile_dimensions * Vector(x, y)
            p2 = tile_dimensions * Vector(x + 1, y + 1)
            orient = random.randrange(4)
            g.matrix = \
                (
                    save_matrix
                *
                    Matrix.scale
                      (
                        factor = Vector((1, -1)[orient & 1 != 0], 1),
                        centre = (p1 + p2) / 2
                      )
                *
                    Matrix.scale
                      (
                        factor = Vector(1, (1, -1)[orient & 2 != 0], ),
                        centre = (p1 + p2) / 2
                      )
                )
            do_tile(g, p1, p2)
        #end for
    #end for
    g.matrix = save_matrix
#end draw_truchet

#+
# Mainline
#-

nr_tiles = Vector(1, 1) * 16
tile_dimensions = Vector(1, 1) * 24
margin = Vector(1, 1) * 20
figure_dimensions = tile_dimensions * nr_tiles
nr_cols = math.ceil(math.sqrt(len(truchet_types)))
nr_rows = math.ceil(len(truchet_types) / nr_cols)
image_dimensions = (figure_dimensions + margin) * Vector(nr_cols, nr_rows) + margin
pix = qah.ImageSurface.create \
  (
    format = CAIRO.FORMAT_RGB24,
    dimensions = image_dimensions
  )
g = \
    (Context.create(pix)
        .set_source_colour(Colour.grey(1))
        .paint()
        .set_source_colour(Colour.grey(0))
        .set_line_width(2)
    )
row = 0
col = 0
for do_tile in truchet_types :
    (g
        .save()
        .translate(margin + Vector(col, row) * (figure_dimensions + margin))
    )
    random = RubbishRandom(999) # want same sequence every time
    draw_truchet \
      (
        g = g,
        do_tile = do_tile,
        total_dimensions = figure_dimensions,
        nr_tiles = nr_tiles,
      )
    g.restore()
    col += 1
    if col == nr_cols :
        col = 0
        row += 1
    #end if
#end for

pix.flush().write_to_png("{}.png".format(os.path.basename(sys.argv[0])))
